document.write( '<script>\n' );
document.write( 'info=\"<body class="body">\n' );
document.write( '\n' );
document.write( '	\n' );
document.write( '	<header class="header">\n' );
document.write( '		<div class="header__wrap">\n' );
document.write( '			<div class="container">\n' );
document.write( '				<div class="row">\n' );
document.write( '					<div class="col-12">\n' );
document.write( '						<div class="header__content">\n' );
document.write( '							\n' );
document.write( '							<a href="index.html" class="header__logo">\n' );
document.write( '\n' );
document.write( '								<img src="img/HappyCelebratedChihuahua-size_restricted.gif" alt="">\n' );
document.write( '\n' );
document.write( '							</a>\n' );
document.write( '							\n' );
document.write( '\n' );
document.write( '							\n' );
document.write( '							<ul class="header__nav">\n' );
document.write( '								\n' );
document.write( '								<li class="header__nav-item">\n' );
document.write( '									<a href="index.html" class="header__nav-link">Home</a>\n' );
document.write( '								</li>\n' );
document.write( '								\n' );
document.write( '\n' );
document.write( '								\n' );
document.write( '								<li class="header__nav-item">\n' );
document.write( '									<a href="catalog1.js" class="header__nav-link">History</a>\n' );
document.write( '								</li>\n' );
document.write( '								\n' );
document.write( '\n' );
document.write( '								<li class="header__nav-item">\n' );
document.write( '									<a href="pricing.js" class="header__nav-link">pricing Plan</a>\n' );
document.write( '								</li>\n' );
document.write( '\n' );
document.write( '								<li class="header__nav-item">\n' );
document.write( '									<a href="help.js" class="header__nav-link">Help</a>\n' );
document.write( '								</li>\n' );
document.write( '\n' );
document.write( '								\n' );
document.write( '								<li class="dropdown header__nav-item">\n' );
document.write( '									<a class="dropdown-toggle header__nav-link header__nav-link--more" href="#"\n' );
document.write( '										role="button" id="dropdownMenuMore" data-toggle="dropdown" aria-haspopup="true"\n' );
document.write( '										aria-expanded="false"><i class="icon ion-ios-more"></i></a>\n' );
document.write( '\n' );
document.write( '									<ul class="dropdown-menu header__dropdown-menu" aria-labelledby="dropdownMenuMore">\n' );
document.write( '										<li><a href="about.js">About</a></li>\n' );
document.write( '										<li><a href="signin.js">Sign In</a></li>\n' );
document.write( '										<li><a href="signup.js">Sign Up</a></li>\n' );
document.write( '										<li><a href="help.js">404 Page</a></li>\n' );
document.write( '									</ul>\n' );
document.write( '								</li>\n' );
document.write( '								\n' );
document.write( '							</ul>\n' );
document.write( '							\n' );
document.write( '\n' );
document.write( '							\n' );
document.write( '							<div class="header__auth">\n' );
document.write( '								<button class="header__search-btn" type="button">\n' );
document.write( '									<i class="icon ion-ios-search"></i>\n' );
document.write( '								</button>\n' );
document.write( '\n' );
document.write( '								<a href="signin.js" class="header__sign-in">\n' );
document.write( '									<i class="icon ion-ios-log-in"></i>\n' );
document.write( '									<span>sign in</span>\n' );
document.write( '								</a>\n' );
document.write( '							</div>\n' );
document.write( '							\n' );
document.write( '\n' );
document.write( '							\n' );
document.write( '							<button class="header__btn" type="button">\n' );
document.write( '								<span></span>\n' );
document.write( '								<span></span>\n' );
document.write( '								<span></span>\n' );
document.write( '							</button>\n' );
document.write( '							\n' );
document.write( '						</div>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '			</div>\n' );
document.write( '		</div>\n' );
document.write( '\n' );
document.write( '		\n' );
document.write( '		<form action="#" class="header__search">\n' );
document.write( '			<div class="container">\n' );
document.write( '				<div class="row">\n' );
document.write( '					<div class="col-12">\n' );
document.write( '						<div class="header__search-content">\n' );
document.write( '							<input type="text" placeholder="Search">\n' );
document.write( '\n' );
document.write( '							<button type="button">search</button>\n' );
document.write( '						</div>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '			</div>\n' );
document.write( '		</form>\n' );
document.write( '		\n' );
document.write( '	</header>\n' );
document.write( '	\n' );
document.write( '\n' );
document.write( '	<!-- home -->\n' );
document.write( '	<section class="home">\n' );
document.write( '		<!-- home bg -->\n' );
document.write( '		<div class="owl-carousel home__bg">\n' );
document.write( '			<div class="item home__cover" data-bg="img/home/home__bg.jpg"></div>\n' );
document.write( '			<div class="item home__cover" data-bg="img/home/home__bg2.jpg"></div>\n' );
document.write( '			<div class="item home__cover" data-bg="img/home/home__bg3.jpg"></div>\n' );
document.write( '			<div class="item home__cover" data-bg="img/home/home__bg4.jpg"></div>\n' );
document.write( '		</div>\n' );
document.write( '		<!-- end home bg -->\n' );
document.write( '\n' );
document.write( '		<div class="container">\n' );
document.write( '			<div class="row">\n' );
document.write( '				<div class="col-12">\n' );
document.write( '					<h1 class="home__title"><b>Trending</b> Now</h1>\n' );
document.write( '\n' );
document.write( '					<button class="home__nav home__nav--prev" type="button">\n' );
document.write( '						<i class="icon ion-ios-arrow-round-back"></i>\n' );
document.write( '					</button>\n' );
document.write( '					<button class="home__nav home__nav--next" type="button">\n' );
document.write( '						<i class="icon ion-ios-arrow-round-forward"></i>\n' );
document.write( '					</button>\n' );
document.write( '				</div>\n' );
document.write( '\n' );
document.write( '				<div class="col-12">\n' );
document.write( '					<div class="owl-carousel home__carousel">\n' );
document.write( '						<div class="item">\n' );
document.write( '							<!-- card -->\n' );
document.write( '							<div class="card card--big">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '							<!-- end card -->\n' );
document.write( '						</div>\n' );
document.write( '\n' );
document.write( '						<div class="item">\n' );
document.write( '							<!-- card -->\n' );
document.write( '							<div class="card card--big">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover2.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '							<!-- end card -->\n' );
document.write( '						</div>\n' );
document.write( '\n' );
document.write( '						<div class="item">\n' );
document.write( '							<!-- card -->\n' );
document.write( '							<div class="card card--big">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover3.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '							<!-- end card -->\n' );
document.write( '						</div>\n' );
document.write( '\n' );
document.write( '						<div class="item">\n' );
document.write( '							<!-- card -->\n' );
document.write( '							<div class="card card--big">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover4.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '							<!-- end card -->\n' );
document.write( '						</div>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '			</div>\n' );
document.write( '		</div>\n' );
document.write( '	</section>\n' );
document.write( '	<!-- end home -->\n' );
document.write( '\n' );
document.write( '	<!-- content -->\n' );
document.write( '	<section class="content">\n' );
document.write( '		<div class="content__head">\n' );
document.write( '			<div class="container">\n' );
document.write( '				<div class="row">\n' );
document.write( '					<div class="col-12">\n' );
document.write( '						<!-- content title -->\n' );
document.write( '						<h2 class="content__title">Trending</h2>\n' );
document.write( '						<!-- end content title -->\n' );
document.write( '\n' );
document.write( '						<!-- content tabs nav -->\n' );
document.write( '						<ul class="nav nav-tabs content__tabs" id="content__tabs" role="tablist">\n' );
document.write( '							<li class="nav-item">\n' );
document.write( '								<a class="nav-link active" data-toggle="tab" href="#tab-1" role="tab"\n' );
document.write( '									aria-controls="tab-1" aria-selected="true">TRENDING/a>\n' );
document.write( '							</li>\n' );
document.write( '\n' );
document.write( '							<li class="nav-item">\n' );
document.write( '								<a class="nav-link" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2"\n' );
document.write( '									aria-selected="false">HISTORY</a>\n' );
document.write( '							</li>\n' );
document.write( '\n' );
document.write( '							<li class="nav-item">\n' );
document.write( '								<a class="nav-link" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3"\n' );
document.write( '									aria-selected="false">LIKED</a>\n' );
document.write( '							</li>\n' );
document.write( '\n' );
document.write( '							<li class="nav-item">\n' );
document.write( '								<a class="nav-link" data-toggle="tab" href="#tab-4" role="tab" aria-controls="tab-4"\n' );
document.write( '									aria-selected="false">SUBSCRIBED</a>\n' );
document.write( '							</li>\n' );
document.write( '						</ul>\n' );
document.write( '						<!-- end content tabs nav -->\n' );
document.write( '\n' );
document.write( '						<!-- content mobile tabs nav -->\n' );
document.write( '						<div class="content__mobile-tabs" id="content__mobile-tabs">\n' );
document.write( '							<div class="content__mobile-tabs-btn dropdown-toggle" role="navigation" id="mobile-tabs"\n' );
document.write( '								data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">\n' );
document.write( '								<input type="button" value="Trending">\n' );
document.write( '								<span></span>\n' );
document.write( '							</div>\n' );
document.write( '\n' );
document.write( '							<div class="content__mobile-tabs-menu dropdown-menu" aria-labelledby="mobile-tabs">\n' );
document.write( '								<ul class="nav nav-tabs" role="tablist">\n' );
document.write( '									<li class="nav-item"><a class="nav-link active" id="1-tab" data-toggle="tab"\n' );
document.write( '											href="#tab-1" role="tab" aria-controls="tab-1"\n' );
document.write( '											aria-selected="true">TRENDING</a></li>\n' );
document.write( '\n' );
document.write( '									<li class="nav-item"><a class="nav-link" id="2-tab" data-toggle="tab" href="#tab-2"\n' );
document.write( '											role="tab" aria-controls="tab-2" aria-selected="false">HISTORY</a></li>\n' );
document.write( '\n' );
document.write( '									<li class="nav-item"><a class="nav-link" id="3-tab" data-toggle="tab" href="#tab-3"\n' );
document.write( '											role="tab" aria-controls="tab-3" aria-selected="false">LIKED</a></li>\n' );
document.write( '\n' );
document.write( '									<li class="nav-item"><a class="nav-link" id="4-tab" data-toggle="tab" href="#tab-4"\n' );
document.write( '											role="tab" aria-controls="tab-4" aria-selected="false">SUBSCRIBED</a></li>\n' );
document.write( '								</ul>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end content mobile tabs nav -->\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '			</div>\n' );
document.write( '		</div>\n' );
document.write( '\n' );
document.write( '		<div class="container">\n' );
document.write( '			<!-- content tabs -->\n' );
document.write( '			<div class="tab-content" id="myTabContent">\n' );
document.write( '				<div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="1-tab">\n' );
document.write( '					<div class="row">\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-12 col-lg-6">\n' );
document.write( '							<div class="card card--list">\n' );
document.write( '								<div class="row">\n' );
document.write( '									<div class="col-12 col-sm-4">\n' );
document.write( '										<div class="card__cover">\n' );
document.write( '											<img src="img/covers/cover.jpg" alt="">\n' );
document.write( '											<a href="#" class="card__play">\n' );
document.write( '												<i class="icon ion-ios-play"></i>\n' );
document.write( '											</a>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '\n' );
document.write( '									<div class="col-12 col-sm-8">\n' );
document.write( '										<div class="card__content">\n' );
document.write( '											<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '											<span class="card__category">\n' );
document.write( '												<a href="#">Action</a>\n' );
document.write( '												<a href="#">Conspiracy</a>\n' );
document.write( '											</span>\n' );
document.write( '\n' );
document.write( '											<div class="card__wrap">\n' );
document.write( '												<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '\n' );
document.write( '												<ul class="card__list">\n' );
document.write( '													<li>HD</li>\n' );
document.write( '													<li>16+</li>\n' );
document.write( '												</ul>\n' );
document.write( '											</div>\n' );
document.write( '\n' );
document.write( '											<div class="card__description">\n' );
document.write( '												<p>It is a long established fact that a reader will be distracted by the\n' );
document.write( '													readable content of a page when looking at its layout. The point of\n' );
document.write( '													using Lorem Ipsum is that it has a more-or-less normal distribution\n' );
document.write( '													of letters, as opposed to using 'Content here, content here', making\n' );
document.write( '													it look like readable English.</p>\n' );
document.write( '											</div>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-12 col-lg-6">\n' );
document.write( '							<div class="card card--list">\n' );
document.write( '								<div class="row">\n' );
document.write( '									<div class="col-12 col-sm-4">\n' );
document.write( '										<div class="card__cover">\n' );
document.write( '											<img src="img/covers/cover2.jpg" alt="">\n' );
document.write( '											<a href="#" class="card__play">\n' );
document.write( '												<i class="icon ion-ios-play"></i>\n' );
document.write( '											</a>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '\n' );
document.write( '									<div class="col-12 col-sm-8">\n' );
document.write( '										<div class="card__content">\n' );
document.write( '											<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '											<span class="card__category">\n' );
document.write( '												<a href="#">Conspiracy</a>\n' );
document.write( '											</span>\n' );
document.write( '\n' );
document.write( '											<div class="card__wrap">\n' );
document.write( '												<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '\n' );
document.write( '												<ul class="card__list">\n' );
document.write( '													<li>HD</li>\n' );
document.write( '													<li>16+</li>\n' );
document.write( '												</ul>\n' );
document.write( '											</div>\n' );
document.write( '\n' );
document.write( '											<div class="card__description">\n' );
document.write( '												<p>Lorem Ipsum is simply dummy text of the printing and typesetting\n' );
document.write( '													industry. Lorem Ipsum has been the industry's standard dummy text\n' );
document.write( '													ever since the 1500s, when an unknown printer took a galley of type\n' );
document.write( '													and scrambled it to make a type specimen book.</p>\n' );
document.write( '											</div>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-12 col-lg-6">\n' );
document.write( '							<div class="card card--list">\n' );
document.write( '								<div class="row">\n' );
document.write( '									<div class="col-12 col-sm-4">\n' );
document.write( '										<div class="card__cover">\n' );
document.write( '											<img src="img/covers/cover3.jpg" alt="">\n' );
document.write( '											<a href="#" class="card__play">\n' );
document.write( '												<i class="icon ion-ios-play"></i>\n' );
document.write( '											</a>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '\n' );
document.write( '									<div class="col-12 col-sm-8">\n' );
document.write( '										<div class="card__content">\n' );
document.write( '											<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '											<span class="card__category">\n' );
document.write( '												<a href="#">Conspiracy</a>\n' );
document.write( '												<a href="#">Conspiracy</a>\n' );
document.write( '												<a href="#">Music</a>\n' );
document.write( '											</span>\n' );
document.write( '\n' );
document.write( '											<div class="card__wrap">\n' );
document.write( '												<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '\n' );
document.write( '												<ul class="card__list">\n' );
document.write( '													<li>HD</li>\n' );
document.write( '													<li>16+</li>\n' );
document.write( '												</ul>\n' );
document.write( '											</div>\n' );
document.write( '\n' );
document.write( '											<div class="card__description">\n' );
document.write( '												<p>It has survived not only five centuries, but also the leap into\n' );
document.write( '													electronic typesetting, remaining essentially unchanged. It was\n' );
document.write( '													popularised in the 1960s with the release of Letraset sheets\n' );
document.write( '													containing Lorem Ipsum passages, and more recently with desktop\n' );
document.write( '													publishing software like Aldus PageMaker including versions of Lorem\n' );
document.write( '													Ipsum.</p>\n' );
document.write( '											</div>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-12 col-lg-6">\n' );
document.write( '							<div class="card card--list">\n' );
document.write( '								<div class="row">\n' );
document.write( '									<div class="col-12 col-sm-4">\n' );
document.write( '										<div class="card__cover">\n' );
document.write( '											<img src="img/covers/cover4.jpg" alt="">\n' );
document.write( '											<a href="#" class="card__play">\n' );
document.write( '												<i class="icon ion-ios-play"></i>\n' );
document.write( '											</a>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '\n' );
document.write( '									<div class="col-12 col-sm-8">\n' );
document.write( '										<div class="card__content">\n' );
document.write( '											<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '											<span class="card__category">\n' );
document.write( '												<a href="#">Conspiracy</a>\n' );
document.write( '												<a href="#">Conspiracy</a>\n' );
document.write( '											</span>\n' );
document.write( '\n' );
document.write( '											<div class="card__wrap">\n' );
document.write( '												<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '\n' );
document.write( '												<ul class="card__list">\n' );
document.write( '													<li>HD</li>\n' );
document.write( '													<li>16+</li>\n' );
document.write( '												</ul>\n' );
document.write( '											</div>\n' );
document.write( '\n' );
document.write( '											<div class="card__description">\n' );
document.write( '												<p>Many desktop publishing packages and web page editors now use Lorem\n' );
document.write( '													Ipsum as their default model text, and a search for 'lorem ipsum'\n' );
document.write( '													will uncover many web sites still in their infancy. Various versions\n' );
document.write( '													have evolved over the years, sometimes by accident, sometimes on\n' );
document.write( '													purpose (injected humour and the like).</p>\n' );
document.write( '											</div>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-12 col-lg-6">\n' );
document.write( '							<div class="card card--list">\n' );
document.write( '								<div class="row">\n' );
document.write( '									<div class="col-12 col-sm-4">\n' );
document.write( '										<div class="card__cover">\n' );
document.write( '											<img src="img/covers/cover5.jpg" alt="">\n' );
document.write( '											<a href="#" class="card__play">\n' );
document.write( '												<i class="icon ion-ios-play"></i>\n' );
document.write( '											</a>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '\n' );
document.write( '									<div class="col-12 col-sm-8">\n' );
document.write( '										<div class="card__content">\n' );
document.write( '											<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '											<span class="card__category">\n' );
document.write( '												<a href="#">Action</a>\n' );
document.write( '												<a href="#">Conspiracy</a>\n' );
document.write( '											</span>\n' );
document.write( '\n' );
document.write( '											<div class="card__wrap">\n' );
document.write( '												<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '\n' );
document.write( '												<ul class="card__list">\n' );
document.write( '													<li>HD</li>\n' );
document.write( '													<li>16+</li>\n' );
document.write( '												</ul>\n' );
document.write( '											</div>\n' );
document.write( '\n' );
document.write( '											<div class="card__description">\n' );
document.write( '												<p>There are many variations of passages of Lorem Ipsum available, but\n' );
document.write( '													the majority have suffered alteration in some form, by injected\n' );
document.write( '													humour, or randomised words which don't look even slightly\n' );
document.write( '													believable. If you are going to use a passage of Lorem Ipsum, you\n' );
document.write( '													need to be sure there isn't anything embarrassing hidden in the\n' );
document.write( '													middle of text.</p>\n' );
document.write( '											</div>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-12 col-lg-6">\n' );
document.write( '							<div class="card card--list">\n' );
document.write( '								<div class="row">\n' );
document.write( '									<div class="col-12 col-sm-4">\n' );
document.write( '										<div class="card__cover">\n' );
document.write( '											<img src="img/covers/cover6.jpg" alt="">\n' );
document.write( '											<a href="#" class="card__play">\n' );
document.write( '												<i class="icon ion-ios-play"></i>\n' );
document.write( '											</a>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '\n' );
document.write( '									<div class="col-12 col-sm-8">\n' );
document.write( '										<div class="card__content">\n' );
document.write( '											<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '											<span class="card__category">\n' );
document.write( '												<a href="#">Conspiracy</a>\n' );
document.write( '											</span>\n' );
document.write( '\n' );
document.write( '											<div class="card__wrap">\n' );
document.write( '												<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '\n' );
document.write( '												<ul class="card__list">\n' );
document.write( '													<li>HD</li>\n' );
document.write( '													<li>16+</li>\n' );
document.write( '												</ul>\n' );
document.write( '											</div>\n' );
document.write( '\n' );
document.write( '											<div class="card__description">\n' );
document.write( '												<p>All the Lorem Ipsum generators on the Internet tend to repeat\n' );
document.write( '													predefined chunks as necessary, making this the first true generator\n' );
document.write( '													on the Internet. It uses a dictionary of over 200 Latin words,\n' );
document.write( '													combined with a handful of model sentence structures, to generate\n' );
document.write( '													Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is\n' );
document.write( '													therefore always free from repetition, injected humour, or\n' );
document.write( '													non-characteristic words etc.</p>\n' );
document.write( '											</div>\n' );
document.write( '										</div>\n' );
document.write( '									</div>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '\n' );
document.write( '				<div class="tab-pane fade" id="tab-2" role="tabpanel" aria-labelledby="2-tab">\n' );
document.write( '					<div class="row">\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Action</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover2.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover3.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Music</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover4.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover5.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Action</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover6.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover6.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Music</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover5.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover4.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Action</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover3.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover2.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Music</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '\n' );
document.write( '				<div class="tab-pane fade" id="tab-3" role="tabpanel" aria-labelledby="3-tab">\n' );
document.write( '					<div class="row">\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover2.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Action</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover4.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Music</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover3.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover6.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Action</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover5.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover5.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Music</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover6.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover3.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Action</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover4.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Music</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover2.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '\n' );
document.write( '				<div class="tab-pane fade" id="tab-4" role="tabpanel" aria-labelledby="4-tab">\n' );
document.write( '					<div class="row">\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Action</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover3.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover2.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Music</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover6.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover4.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Action</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover5.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover6.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Music</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover5.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover4.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Action</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover3.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover2.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Music</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '\n' );
document.write( '						<!-- card -->\n' );
document.write( '						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '							<div class="card">\n' );
document.write( '								<div class="card__cover">\n' );
document.write( '									<img src="img/covers/cover.jpg" alt="">\n' );
document.write( '									<a href="#" class="card__play">\n' );
document.write( '										<i class="icon ion-ios-play"></i>\n' );
document.write( '									</a>\n' );
document.write( '								</div>\n' );
document.write( '								<div class="card__content">\n' );
document.write( '									<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '									<span class="card__category">\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '										<a href="#">Conspiracy</a>\n' );
document.write( '									</span>\n' );
document.write( '									<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '								</div>\n' );
document.write( '							</div>\n' );
document.write( '						</div>\n' );
document.write( '						<!-- end card -->\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '			</div>\n' );
document.write( '			\n' );
document.write( '		</div>\n' );
document.write( '	</section>\n' );
document.write( '	\n' );
document.write( '\n' );
document.write( '	\n' );
document.write( '	<section class="section section--bg" data-bg="img/section/section.jpg">\n' );
document.write( '		<div class="container">\n' );
document.write( '			<div class="row">\n' );
document.write( '				\n' );
document.write( '				<div class="col-12">\n' );
document.write( '					<h2 class="section__title">History</h2>\n' );
document.write( '				</div>\n' );
document.write( '				\n' );
document.write( '\n' );
document.write( '				<!-- card -->\n' );
document.write( '				<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '					<div class="card">\n' );
document.write( '						<div class="card__cover">\n' );
document.write( '							<img src="img/covers/cover.jpg" alt="">\n' );
document.write( '							<a href="#" class="card__play">\n' );
document.write( '								<i class="icon ion-ios-play"></i>\n' );
document.write( '							</a>\n' );
document.write( '						</div>\n' );
document.write( '						<div class="card__content">\n' );
document.write( '							<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '							<span class="card__category">\n' );
document.write( '								<a href="#">Action</a>\n' );
document.write( '								<a href="#">Conspiracy</a>\n' );
document.write( '							</span>\n' );
document.write( '							<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '						</div>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<!-- end card -->\n' );
document.write( '\n' );
document.write( '				<!-- card -->\n' );
document.write( '				<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '					<div class="card">\n' );
document.write( '						<div class="card__cover">\n' );
document.write( '							<img src="img/covers/cover3.jpg" alt="">\n' );
document.write( '							<a href="#" class="card__play">\n' );
document.write( '								<i class="icon ion-ios-play"></i>\n' );
document.write( '							</a>\n' );
document.write( '						</div>\n' );
document.write( '						<div class="card__content">\n' );
document.write( '							<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '							<span class="card__category">\n' );
document.write( '								<a href="#">Conspiracy</a>\n' );
document.write( '							</span>\n' );
document.write( '							<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '						</div>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<!-- end card -->\n' );
document.write( '\n' );
document.write( '				<!-- card -->\n' );
document.write( '				<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '					<div class="card">\n' );
document.write( '						<div class="card__cover">\n' );
document.write( '							<img src="img/covers/cover2.jpg" alt="">\n' );
document.write( '							<a href="#" class="card__play">\n' );
document.write( '								<i class="icon ion-ios-play"></i>\n' );
document.write( '							</a>\n' );
document.write( '						</div>\n' );
document.write( '						<div class="card__content">\n' );
document.write( '							<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '							<span class="card__category">\n' );
document.write( '								<a href="#">Conspiracy</a>\n' );
document.write( '								<a href="#">Conspiracy</a>\n' );
document.write( '								<a href="#">Music</a>\n' );
document.write( '							</span>\n' );
document.write( '							<span class="card__rate"><i class="icon ion-ios-star"></i>6.3</span>\n' );
document.write( '						</div>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<!-- end card -->\n' );
document.write( '\n' );
document.write( '				<!-- card -->\n' );
document.write( '				<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '					<div class="card">\n' );
document.write( '						<div class="card__cover">\n' );
document.write( '							<img src="img/covers/cover6.jpg" alt="">\n' );
document.write( '							<a href="#" class="card__play">\n' );
document.write( '								<i class="icon ion-ios-play"></i>\n' );
document.write( '							</a>\n' );
document.write( '						</div>\n' );
document.write( '						<div class="card__content">\n' );
document.write( '							<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '							<span class="card__category">\n' );
document.write( '								<a href="#">Conspiracy</a>\n' );
document.write( '								<a href="#">Conspiracy</a>\n' );
document.write( '							</span>\n' );
document.write( '							<span class="card__rate"><i class="icon ion-ios-star"></i>7.9</span>\n' );
document.write( '						</div>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<!-- end card -->\n' );
document.write( '\n' );
document.write( '				<!-- card -->\n' );
document.write( '				<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '					<div class="card">\n' );
document.write( '						<div class="card__cover">\n' );
document.write( '							<img src="img/covers/cover4.jpg" alt="">\n' );
document.write( '							<a href="#" class="card__play">\n' );
document.write( '								<i class="icon ion-ios-play"></i>\n' );
document.write( '							</a>\n' );
document.write( '						</div>\n' );
document.write( '						<div class="card__content">\n' );
document.write( '							<h3 class="card__title"><a href="#">I Dream in Another Language</a></h3>\n' );
document.write( '							<span class="card__category">\n' );
document.write( '								<a href="#">Action</a>\n' );
document.write( '								<a href="#">Conspiracy</a>\n' );
document.write( '							</span>\n' );
document.write( '							<span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>\n' );
document.write( '						</div>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<!-- end card -->\n' );
document.write( '\n' );
document.write( '				<!-- card -->\n' );
document.write( '				<div class="col-6 col-sm-4 col-lg-3 col-xl-2">\n' );
document.write( '					<div class="card">\n' );
document.write( '						<div class="card__cover">\n' );
document.write( '							<img src="img/covers/cover5.jpg" alt="">\n' );
document.write( '							<a href="#" class="card__play">\n' );
document.write( '								<i class="icon ion-ios-play"></i>\n' );
document.write( '							</a>\n' );
document.write( '						</div>\n' );
document.write( '						<div class="card__content">\n' );
document.write( '							<h3 class="card__title"><a href="#">I am a video</a></h3>\n' );
document.write( '							<span class="card__category">\n' );
document.write( '								<a href="#">Conspiracy</a>\n' );
document.write( '							</span>\n' );
document.write( '							<span class="card__rate"><i class="icon ion-ios-star"></i>7.1</span>\n' );
document.write( '						</div>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<!-- end card -->\n' );
document.write( '\n' );
document.write( '			</div>\n' );
document.write( '		</div>\n' );
document.write( '	</section>\n' );
document.write( '	<!-- end History -->\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '	<\n' );
document.write( '	<footer class="footer">\n' );
document.write( '		<div class="container">\n' );
document.write( '			<div class="row">\n' );
document.write( '				\n' );
document.write( '				<div class="col-12 col-md-3">\n' );
document.write( '					<h6 class="footer__title">Download Our App</h6>\n' );
document.write( '					<ul class="footer__app">\n' );
document.write( '						<li><a href="appstore.com"><img src="img/Download_on_the_App_Store_Badge.svg" alt=""></a></li>\n' );
document.write( '						<li><a href="https://play.google.com/store"><img src="img/google-play-badge.png" alt=""></a>\n' );
document.write( '						</li>\n' );
document.write( '					</ul>\n' );
document.write( '				</div>\n' );
document.write( '				\n' );
document.write( '\n' );
document.write( '				\n' );
document.write( '				<div class="col-6 col-sm-4 col-md-3">\n' );
document.write( '					<h6 class="footer__title">Resources</h6>\n' );
document.write( '					<ul class="footer__list">\n' );
document.write( '						<li><a href="help.js">About Us</a></li>\n' );
document.write( '						<li><a href="help.js"></a></li>\n' );
document.write( '						<li><a href="help.js">Help</a></li>\n' );
document.write( '					</ul>\n' );
document.write( '				</div>\n' );
document.write( '				\n' );
document.write( '\n' );
document.write( '				\n' );
document.write( '				<div class="col-6 col-sm-4 col-md-3">\n' );
document.write( '					<h6 class="footer__title">Legal</h6>\n' );
document.write( '					<ul class="footer__list">\n' );
document.write( '						<li><a href="#">Terms of Use</a></li>\n' );
document.write( '						<li><a href="#">Privacy Policy</a></li>\n' );
document.write( '						<li><a href="#">Security</a></li>\n' );
document.write( '					</ul>\n' );
document.write( '				</div>\n' );
document.write( '				\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '				\n' );
document.write( '				<div class="col-12 col-sm-4 col-md-3">\n' );
document.write( '					<h6 class="footer__title">Contact</h6>\n' );
document.write( '					<ul class="footer__list">\n' );
document.write( '						<li><a href="tel:+18001231212">+1 (800) 123-1212</a></li>\n' );
document.write( '						<li><a href="mailto:support@moviego.com">support@nomorecensorship.com</a></li>\n' );
document.write( '					</ul>\n' );
document.write( '					<ul class="footer__social">\n' );
document.write( '						<li class="facebook"><a href="https://www.facebook.com"><i\n' );
document.write( '									class="icon ion-logo-facebook"></i></a></li>\n' );
document.write( '						<li class="instagram"><a href="https://www.instagram.com/"><i\n' );
document.write( '									class="icon ion-logo-instagram"></i></a></li>\n' );
document.write( '						<li class="twitter"><a href="https://twitter.com"><i class="icon ion-logo-twitter"></i></a></li>\n' );
document.write( '					</ul>\n' );
document.write( '				</div>\n' );
document.write( '				\n' );
document.write( '\n' );
document.write( '			</div>\n' );
document.write( '		</div>\n' );
document.write( '	</footer>\n' );
document.write( '	\"\n' );
document.write( '\n' );
document.write( 'document.write(info)\n' );
document.write( '</script>' );
